import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Header, Sidebar } from "../components";
// import Providers from "./storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`lg:h-screen h-full bg-[#04050C] ${geistSans.variable} ${geistMono.variable} antialiased  `}
        style={{ overflow: "hidden", position: "relative" }}
      >
        {/* <Providers> */}
        {/* <Theme className=""> */}
        <div className="bg-[#04050C] min-h-screen relative overflow-x-hidden flex flex-col">
          <Header />
          <div className="flex z-1 relative grow flex-1 h-full">
            <div className="md:flex hidden h-[calc(100vh-72px)]">
              <Sidebar />
            </div>
            <div className="flex-grow overflow-y-auto">{children}</div>
          </div>
          <div className="absolute  right-0 bottom-0 bg-[#1B3E90]  rounded-full z-[0] w-[1200px] h-[650px]  top-1/2 left-1/2 blur-[300px] -translate-x-1/2 -translate-y-1/2"></div>
        </div>
        {/* </Theme> */}
      </body>
    </html>
  );
}
